<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimpleTaskApp.Core\SimpleTaskApp.Core.csproj" />
    <ProjectReference Include="..\SimpleTaskApp.Data\SimpleTaskApp.Data.csproj" />
  </ItemGroup>
</Project>
